sudo: false

language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - pypy

install:
  - pip install pip setuptools --upgrade
  - pip install -r requirements.txt
  - pip install -e .[all]
  - pip install tox tox-travis

script:
  - # python setup.py pytest
  - py.test -v test/
  - # python setup.py tox
  - tox -r -v

deploy:
  provider: pypi
  user: userzimmermann
  password:
    secure: joxW8Q5vKhvoulK4hj2wDzWrW5RazZn+nFaKDqwxXsTGffC+8YrhL8Z+zKgn6tlh7pOYnni35pA9iMW6UasUIop/Zblt4ZqKQVTWlbQfBEp8pxXniWIvJtIdjMFIkmtDu57VsEKwcrY5bBmzDoy0GRjtRJIMyRS0vGMj6MgwZaz1A/YT3spr8AWnvXsOcUVexO7Jde6JuDsmiBrddRqaVmxRcNRAprmdLuqcDPG2lCKbUr4ZfwqDsA0gMc6uT1Kgt9Hq9qhT8iwx9+Fio5SJeOfbWH1j1ddXTpZRmuvc0utEiVzKYV6VDQbNS88dJet2PCy8FDOYEZ/uNYJdwZ0yeZdrNgCudeRKxE1gazwiealCzLFMejH0BUf4/7erEllzXRzeLpUtGiZW08rd6gRm9FCe8bE8pkDcTEHmUL96kA1dfKwAufCLOWMGvvz/YasJC2SZhml1n/5FeCPEsURNYV44Uyki5pOekwC/zwb646Se0ZYqskkl9m91nVvfIOJWaEZwzoru/UCnNJ9yiYP2pEJYuACZV6ZYXR6jT+ZW/8QZVqQbjSgLlETaUjW3kudaC73FxMmwrWAIP7PenYeBcgHLEiv3uDYlPKJLmvgvtOYmFS7wBdFJgXLKZxUnvBC83FSiFxR75OCDxLgMc9heH/UaccRwzbKYw9tqNw7/wV8=
