sudo: false

language: python
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - pypy

install:
  - pip install -r requirements.txt
  - pip install -r requirements.commands.txt
  - pip install -r requirements.notebook.txt
  - pip install -r requirements.pytest.txt
  - pip install tox
  - pip uninstall zetup --yes
  - pip install -e .

script:
  - python setup.py pytest
  - py.test -v test/
  - python setup.py tox
  - tox -r -v
